TMSolution\GamificationBundle\Entity\Classname:
    type: entity
    table: classname
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
