TMSolution\GamificationBundle\Entity\Event:
    type: entity
    table: event
    indexes:
        fk_event_eventcategory1_idx:
            columns:
                - eventcategoryid
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        eventcategoryid:
            targetEntity: Eventcategory
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                eventcategoryid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
