TMSolution\GamificationBundle\Entity\Eventlog:
    type: entity
    table: eventlog
    indexes:
        fk_usereventlog_event1_idx:
            columns:
                - eventid
        fk_eventlog_object1_idx:
            columns:
                - objectid
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        objectid:
            targetEntity: Objectinstance
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                objectid:
                    referencedColumnName: id
            orphanRemoval: false
        eventid:
            targetEntity: Event
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                eventid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
