TMSolution\GamificationBundle\Entity\Objectinstance:
    type: entity
    table: objectinstance
    indexes:
        fk_object_class1_idx:
            columns:
                - classid
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        objectidentity:
            type: bigint
            nullable: true
            unsigned: false
            comment: ''
    manyToOne:
        classid:
            targetEntity: Classname
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                classid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
