TMSolution\GamificationBundle\Entity\Objecttrophy:
    type: entity
    table: objecttrophy
    indexes:
        fk_usertrophy_trophy1_idx:
            columns:
                - trophyid
        fk_usertrophy_object1_idx:
            columns:
                - objectid
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        date:
            type: datetime
            nullable: true
            comment: ''
    manyToOne:
        objectid:
            targetEntity: Objectinstance
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                objectid:
                    referencedColumnName: id
            orphanRemoval: false
        trophyid:
            targetEntity: Trophy
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trophyid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
