TMSolution\GamificationBundle\Entity\Rule:
    type: entity
    table: rule
    indexes:
        fk_rule_trophy1_idx:
            columns:
                - trophyid
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: true
            length: 255
            fixed: false
            comment: ''
    manyToOne:
        trophyid:
            targetEntity: Trophy
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                trophyid:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
