tm_solution_gamification_homepage:
    path:     /gamification/test/{objectIdentity}/{classId}
    defaults: { _controller: TMSolutionGamificationBundle:Default:check }

tm_solution_gamification_checkTrophy:
    path:     /gamification/checkTrophy/{objectInstance}/{trophyCategory}
    defaults: { _controller: TMSolutionGamificationBundle:Default:checkTrophy }
    
tm_solution_gamification_checkTrophy1:
    path:     /gamification/checkTrophy/{objectInstance}
    defaults: { _controller: TMSolutionGamificationBundle:Default:checkTrophy }
    
tm_solution_gamification_addTrophy1:
    path:     /gamification/addTrophy/{objectInstanceId}/{trophyId}
    defaults: { _controller: TMSolutionGamificationBundle:Default:addTrophy }
    
tm_solution_gamification_checkRule:
    path:     /gamification/checkRule/{objectId}
    defaults: { _controller: TMSolutionGamificationBundle:Default:checkRule }