services:
    gamification.events:
        class: TMSolution\GamificationBundle\Service\EventsService
        arguments: [@service_container]

#listener exception      
#    kernel.listener.your_listener_name:
#        class: TMSolution\GamificationBundle\EventListener\GamificationExceptionListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }           
            
#listener response
#    kernel.listener.your_listener_response:
#        class: TMSolution\GamificationBundle\EventListener\GamificationResponseListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

#    app.tokens.action_listener:
#        class: TMSolution\GamificationBundle\EventListener\GamificationResponseListener
#        arguments: ["%tokens%"]
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }