services:
    gamification.events:
        class: TMSolution\GamificationBundle\Service\GamificationEventsService
        arguments: [@service_container]
    
    gamification.pusher:
        class: TMSolution\GamificationBundle\Service\GamificationPusherService
        arguments: [@service_container]
        tags:
            - { name: gos_web_socket.periodic }
            - { name: gos_web_socket.topic }
    



    event_listener_supervisor_jobmarketad_before_list:
        class: 'TMSolution\GamificationBundle\Model\GamerTrophy'
        arguments: ["@service_container", "TMSolution\GamificationBundle\Entity\GamerTrophy"]
        tags:
         - { name: kernel.event_listener, event: supervisor.jobmarketad.before.list, method: test }

